version: 0.2

env:    
  variables:
    s3_bucket: "$s3_bucket"
    cloudfront: "$cloudfront"

phases: 
      
  build:
    commands:
      - echo deleting...
      - aws s3 rm s3://${s3_bucket} --recursive
