version: 0.2

env:    
  variables:
    s3_bucket: "$s3_bucket"
    cloudfront: "$cloudfront"
    api: "$api"

phases:

  install:
    commands:
      - n 18
      - npm i npm@latest -g
      - npm i
      
  build:
    commands:
      - grep -q '^CLOUDFRONT=' .env.local && sed -i "s/^CLOUDFRONT=.*/CLOUDFRONT=$cloudfront/" .env.local || echo "CLOUDFRONT=$cloudfront" >> .env.local
      - grep -q '^API=' .env.production && sed -i "s/^API=.*/API=$api/" .env.production || echo "API=$api" >> .env.production
      - npm run build     
      - mkdir -p temp/_next/static && cp -r .next/static temp/_next
      - zip -r9 temp/lambda.zip .next package.json package-lock.json next.config.js run.sh server.js public
      - cd temp
      - aws s3 rm s3://${s3_bucket} --recursive
      - aws s3 sync . s3://${s3_bucket}
