version: 0.2

env:    
  variables:
    s3_bucket: "$s3_bucket"

phases:

  install:
    commands:
      - n 18
      - npm i npm@latest -g
      - npm i
      
  build:
    commands:
      - npm run build      
      - cd out
      - aws s3 rm s3://${s3_bucket} --recursive
      - aws s3 sync . s3://${s3_bucket}
